version: "2.2"

services:
  base:
    build:
      context: ./base
    image: ${DOCKER_REGISTRY:-dccn}/dicomdf-base:${DOCKER_IMAGE_TAG:-latest}
    networks:
      - nw-dicom-dataflow
  orthanc:
    build:
      context: ./orthanc
      args:
        orthanc_version: ${ORTHANC_VERSION:-1.4.2}
    image: ${DOCKER_REGISTRY:-dccn}/dicomdf-orthanc:${ORTHANC_VERSION:-latest}-${ORTHANC_BUILD:-1}
    networks:
      - nw-dicom-dataflow
    hostname: orthanc
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ${VOL_ORTHANC_CONFIG:-./orthanc/config}:/var/lib/orthanc/etc:ro
      - ${VOL_ORTHANC_LOG:-vol-orthanc-log}:/var/lib/orthanc/log
      - ${VOL_ORTHANC_DB:-vol-orthanc-db}:/var/lib/orthanc/db
      - ${VOL_ORTHANC_IDX:-vol-orthanc-idx}:/var/lib/orthanc/idx
    environment:
      - STREAMER_URL=http://streamer:3001
  wlbroker:
    build: 
      context: ./wlbroker
      args:
        base_image: ${DOCKER_REGISTRY:-dccn}/dicomdf-base:${DOCKER_IMAGE_TAG:-latest}
    image: ${DOCKER_REGISTRY:-dccn}/dicomdf-wlbroker:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - base
    networks:
      - nw-dicom-dataflow
    hostname: wlbroker
    ports:
      - 1234:1234
    volumes:
      - ${VOL_WLBROKER:-vol-wlbroker}:/data/wlbroker
  cal2wl:
    build:
      context: ./cal2wl
      args:
        base_image: ${DOCKER_REGISTRY:-dccn}/dicomdf-base:${DOCKER_IMAGE_TAG:-latest}
        tg_toolset_tag: ${TG_TOOLSET_TAG:-1.9.0}
    image: ${DOCKER_REGISTRY:-dccn}/dicomdf-cal2wl:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - base
    networks:
      - nw-dicom-dataflow
    hostname: cal2wl
    volumes:
      - ${VOL_CAL2WL_CONFIG:-./cal2wl/config}:/opt/config:ro
      - ${VOL_WLBROKER:-vol-wlbroker}:/data/wlbroker

networks:
  nw-dicom-dataflow:
    external: true

volumes:
  vol-orthanc-db:
    external: true
  vol-orthanc-idx:
    external: true
  vol-orthanc-log:
    external: true
  vol-wlbroker:
    external: true
